In [1]:
import numpy as np 

In [2]:
A = np.random.randint(1,25,27)
print(A)

[ 7 11  5 18 15 21 18 15 20 14 12  1 11 15 10  5 17 13 20  4 22 15 14 20
 16  1 10]


In [9]:
A = A.reshape((3,3,3))

In [12]:
print(A)

[[[ 7 11  5]
  [18 15 21]
  [18 15 20]]

 [[14 12  1]
  [11 15 10]
  [ 5 17 13]]

 [[20  4 22]
  [15 14 20]
  [16  1 10]]]


In [20]:
A[0,0:3,0]

array([ 7, 18, 18])